name: Publish

on:
  push:
    branches:
      - master
      - 'release'
    paths-ignore:
      - '*.commits'
      - '*.markdown'
      - '**/*.markdown'

env:
  LC_ALL: en_US.UTF-8

jobs:
  PublishSnapshots:
    if: (github.repository == 'liferay/liferay-blade-cli') && (github.ref == 'refs/heads/master')
    name: Publish Snapshots
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        env:
          LIFERAY_NEXUS_USERNAME: ${{ secrets.liferay_nexus_username }}
          LIFERAY_NEXUS_PASSWORD: ${{ secrets.liferay_nexus_password }}
        shell: bash
        run: |
          ./publish.sh snapshots --remote
  PublishRelease:
    if: (github.repository == 'liferay/liferay-blade-cli') && (github.ref == 'refs/heads/release')
    name: Publish Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        env:
          LIFERAY_NEXUS_USERNAME: ${{ secrets.liferay_nexus_username }}
          LIFERAY_NEXUS_PASSWORD: ${{ secrets.liferay_nexus_password }}
        shell: bash
        run: |
          ./publish.sh release --remote